# Generated by Django 5.2 on 2025-10-02 07:47

import django.core.validators
import django.utils.timezone
import re
import useraccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='Enter a valid username. This value may contain only English letters, numbers, and ./_ characters.', regex='^[\\w.]+\\Z')], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='New Email')),
                ('is_account_verified', models.BooleanField(default=False, verbose_name='Is Account Verified?')),
                ('is_new_email_verified', models.BooleanField(default=True, verbose_name='Is New Email Verified?')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=useraccount.models.define_profile_picture_directory, verbose_name='Profile Picture')),
                ('background_picture', models.ImageField(blank=True, null=True, upload_to=useraccount.models.define_background_picture_directory, verbose_name='Background Picture')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Account Private?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'useraccount',
            },
        ),
    ]
