# Generated by Django 5.2 on 2025-10-02 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('otp', '0001_initial'),
        ('plan', '0002_initial'),
        ('useraccount', '0001_initial'),
        ('useraccountconnection', '0001_initial'),
        ('useraccountsubscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='blocking',
            field=models.ManyToManyField(related_name='blocked_by', through='useraccountconnection.BlockList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='following',
            field=models.ManyToManyField(related_name='follower', through='useraccountconnection.FollowingFollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='otp_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otp.otpcode', verbose_name='OTP Code Object'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribed_users', through='useraccountsubscription.Subscription', to='plan.plan'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
