# Generated by Django 5.2 on 2025-10-02 07:47

import django.db.models.deletion
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('like', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=post.models.user_directory_path, validators=[post.models.validate_file_type])),
                ('blurred_file', models.ImageField(blank=True, null=True, upload_to=post.models.blurred_user_directory_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Caption')),
                ('is_open_to_comment', models.BooleanField(default=True, verbose_name='Is Open to Write Comment?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('likes', models.ManyToManyField(related_name='liked_posts', to='like.postlike', verbose_name='Likes')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plan.plan', verbose_name='Plan')),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
    ]
