# Generated by Django 5.2 on 2025-10-02 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), _connector='OR'), name='discount_percent_range_constraint', violation_error_message='Discount percent can not be greater than 100.00 or less than 0.00'),
        ),
    ]
