# Generated by Django 5.2 on 2025-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccountsubscription', '0002_remove_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_subscription_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
